dist: trusty
language: node_js

branches:
  only:
  - master

matrix:
  include:
    - env: FLAKE8
      language: python
      python: "3.6"
      cache: pip
      before_install: ''
      install: pip install flake8==3.7.1
      before_script: ''
      script: flake8

    - env: PRETTIER
      node_js: "10"
      before_install: cd ESSArch_PP/frontend/static/frontend
      install: yarn
      before_script:
      script: yarn prettier --check "**/*.{js,scss,html}"


node_js:
  - 8
  - 9
  - 10
cache:
  yarn: true
  directories:
    - .npm
install:
  - git clone https://github.com/ESSolutions/ESSArch_Core "$HOME/core"
  - export EC_FRONTEND="$HOME/core/ESSArch_Core/frontend"
  - cd ESSArch_PP/frontend/static/frontend
  - yarn
script:
  - yarn test
