dist: trusty
language: node_js

branches:
  only:
  - master

matrix:
  include:
    - env: PRETTIER
      node_js: "10"
      before_install: cd ESSArch_PP/frontend/static/frontend
      install: yarn
      before_script:
      script: yarn prettier --check **/*.js **/*.scss **/*.html

node_js:
  - 8
  - 9
  - 10
cache:
  yarn: true
  directories:
    - .npm
install:
  - git clone https://github.com/ESSolutions/ESSArch_Core "$HOME/core"
  - export EC_FRONTEND="$HOME/core/ESSArch_Core/frontend"
  - cd ESSArch_PP/frontend/static/frontend
  - yarn
script:
  - yarn test
