version: '3'

services:
  db:
    image: "mariadb:10.2.16"
    ports:
      - 3003:3306
    environment:
      MYSQL_DATABASE: epp
      MYSQL_USER: arkiv
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - 15003:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  redis:
    image: redis
    ports:
      - 6003:6379

  elasticsearch:
    build:
      context: docker/elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9203:9200"
      - "9303:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
      build:
          context: docker/logstash
          args:
              ELK_VERSION: $ELK_VERSION
      volumes:
          - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
          - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
      ports:
          - "5003:5000"
          - "9603:9600"
      environment:
          LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
          - elk
      depends_on:
          - elasticsearch

  kibana:
      build:
          context: docker/kibana
          args:
              ELK_VERSION: $ELK_VERSION
      volumes:
          - ./docker/kibana/config/:/usr/share/kibana/config:ro
      ports:
          - "5603:5601"
      networks:
          - elk
      depends_on:
          - elasticsearch

networks:
  elk:
    driver: bridge
