# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('msg', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('alarm', models.IntegerField(default=0)),
                ('alarm_num', models.IntegerField(default=0)),
                ('alarm_sub', models.TextField(blank=True)),
                ('alarm_msg', models.TextField(blank=True)),
                ('checked', models.DateTimeField(default=b'2014-01-01 00:01')),
            ],
            options={
                'permissions': (('list_monitoringobject', 'Can list monitoringobject'),),
            },
        ),
    ]
